/**
 * Cloudflare Worker entry point.
 *
 * Re-exports the SvelteKit worker (HTTP handler) and all Durable Object
 * classes so wrangler can discover them from a single entrypoint.
 */

// SvelteKit HTTP handler (generated by adapter-cloudflare)
export { default } from './.svelte-kit/cloudflare/_worker.js';

// Durable Object classes
export { ChatRoom } from './src/lib/server/chat-room';
